; Copyright (C) Yagnesh Raghava Yakkala. http://yagnesh.org
; Created: Thursday, July 19 2018

load "$nsc/generic.ncl"
load "$nsc/resources.ncl"

;_____________________________________________________________________________
; Function: eradiag_set_tm
; Doc:
;_____________________________________________________________________________
undef("eradiag_set_tm")
function eradiag_set_tm(res_in)
local res_in

begin
  return(res_in)
end
